### ISSUE TITLE
Giving the full file path to --output causes an error

### ISSUE THREAD

**Issue by Spicadox** [pekopekopirate/ytarchive-raw-go#1]
Command: `./ytarchive-raw-go -t 2 -i jsons/rtVwovu_0jM.1.json -o "/home/pi/auto-ytarchive-raw/$(title)s/%(title)s"`
Output: `lock.go:15: Failed to lock file: open /home/pi/auto-ytarchive-raw/【リズム天国】アイドルだからリズム力鍛えなきゃ！！✨【ホロライブ_夜空メル】/【リズム天国】アイドルだからリズム力鍛えなきゃ！！✨【ホロライブ_夜空メル】.mkv.lock: no such file or directory`

Whenever I supply a full file path(complete directory path and filename) it causes an error of no such file or directory. I have tested this on windows and linux and both time it has failed as it would seem `-o` can only take the filename and not the actual path? 
edit: I am using v1.5.4
edit2: Seems that since $(title)s folder doesn't exist before the program runs and the program doesn't create the folder, the program fails and hence the error

**Comment by pekopekopirate** [comment]
Fixed in latest version (it creates the target dir if needed)
