### ISSUE TITLE
Is this unsafe software?

### ISSUE THREAD

**Issue by ev0tto** [pekopekopirate/ytarchive-raw-go#2]
https://www.virustotal.com/gui/file/ea68ce5b17e81a1750990c44e819aaf3dda721055634718fb7217104beaed2b2

<details><summary>Virustotal</summary>

![image](https://user-images.githubusercontent.com/80548883/146659559-7675b8d9-744e-4f69-a2f3-a6de3125b358.png)
</details><br/>

**Comment by pekopekopirate** [comment]
No, but it's written in go and some stupid AV software decides that every single program written in go is malware
